// ─────────────────────────────────────────────────────────────────────────
// Env augmentations
// ─────────────────────────────────────────────────────────────────────────
//
// `worker-configuration.d.ts` is regenerated by `wrangler types`. That
// file types BINDINGS (DOs, R2, Vectorize, AI…) and VARS, but it
// doesn't know about SECRETS, since they live in `.dev.vars` /
// `wrangler secret put` and never touch wrangler.jsonc.
//
// So we declare them here. Adding a new secret? Add it both here AND
// in `.dev.vars.example`.
//
// (For the DO stub typing, see the cast in `worker/index.ts` —
// wrangler emits the namespace without a class generic, so RPC calls
// need a one-line cast at the call site.)
// ─────────────────────────────────────────────────────────────────────────

declare global {
  // Augment the base interface that `Env` extends. The generated
  // wrangler types do `interface __BaseEnv_Env { ... }` and
  // `interface Env extends __BaseEnv_Env {}`, so augmenting the base
  // is picked up everywhere `Env` is used.
  interface __BaseEnv_Env {
    API_TOKEN: string;
    // Optional: the Live Market Room falls back to a documented dev token
    // when this isn't set, so the poll room works out of the box.
    LIVE_ROOM_TOKEN?: string;
    // Optional until Market Memory reads/writes start. See worker/supabase.ts.
    SUPABASE_URL?: string;
    SUPABASE_ANON_KEY?: string;
    // Server-only. Prefer ANON for RLS-aware reads; use this to bypass RLS.
    SUPABASE_SERVICE_ROLE_KEY?: string;
    // Optional. Direct OpenAI TTS. If unset, Voice uses API_TOKEN + AI Gateway.
    OPENAI_API_KEY?: string;
  }
}

export {};
